// Generated by gencpp from file msg_pkg2/MABX.msg
// DO NOT EDIT!


#ifndef MSG_PKG2_MESSAGE_MABX_H
#define MSG_PKG2_MESSAGE_MABX_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace msg_pkg2
{
template <class ContainerAllocator>
struct MABX_
{
  typedef MABX_<ContainerAllocator> Type;

  MABX_()
    : BmAngDH(0.0)  {
    }
  MABX_(const ContainerAllocator& _alloc)
    : BmAngDH(0.0)  {
  (void)_alloc;
    }



   typedef float _BmAngDH_type;
  _BmAngDH_type BmAngDH;





  typedef boost::shared_ptr< ::msg_pkg2::MABX_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::msg_pkg2::MABX_<ContainerAllocator> const> ConstPtr;

}; // struct MABX_

typedef ::msg_pkg2::MABX_<std::allocator<void> > MABX;

typedef boost::shared_ptr< ::msg_pkg2::MABX > MABXPtr;
typedef boost::shared_ptr< ::msg_pkg2::MABX const> MABXConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::msg_pkg2::MABX_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::msg_pkg2::MABX_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace msg_pkg2

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'msg_pkg2': ['/home/nvidia/ROS_Tutorials/catkin_ws/src/ros_python/package_ws/message_generation/msg_pkg2/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::msg_pkg2::MABX_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::msg_pkg2::MABX_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::msg_pkg2::MABX_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::msg_pkg2::MABX_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::msg_pkg2::MABX_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::msg_pkg2::MABX_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::msg_pkg2::MABX_<ContainerAllocator> >
{
  static const char* value()
  {
    return "2a1021f6dea66760b4bec501734d53e5";
  }

  static const char* value(const ::msg_pkg2::MABX_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x2a1021f6dea66760ULL;
  static const uint64_t static_value2 = 0xb4bec501734d53e5ULL;
};

template<class ContainerAllocator>
struct DataType< ::msg_pkg2::MABX_<ContainerAllocator> >
{
  static const char* value()
  {
    return "msg_pkg2/MABX";
  }

  static const char* value(const ::msg_pkg2::MABX_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::msg_pkg2::MABX_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 BmAngDH\n\
";
  }

  static const char* value(const ::msg_pkg2::MABX_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::msg_pkg2::MABX_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.BmAngDH);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct MABX_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::msg_pkg2::MABX_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::msg_pkg2::MABX_<ContainerAllocator>& v)
  {
    s << indent << "BmAngDH: ";
    Printer<float>::stream(s, indent + "  ", v.BmAngDH);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MSG_PKG2_MESSAGE_MABX_H
