// Generated by gencpp from file srv_sub_pub/AddTwoInts.msg
// DO NOT EDIT!


#ifndef SRV_SUB_PUB_MESSAGE_ADDTWOINTS_H
#define SRV_SUB_PUB_MESSAGE_ADDTWOINTS_H

#include <ros/service_traits.h>


#include <srv_sub_pub/AddTwoIntsRequest.h>
#include <srv_sub_pub/AddTwoIntsResponse.h>


namespace srv_sub_pub
{

struct AddTwoInts
{

typedef AddTwoIntsRequest Request;
typedef AddTwoIntsResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct AddTwoInts
} // namespace srv_sub_pub


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::srv_sub_pub::AddTwoInts > {
  static const char* value()
  {
    return "6a2e34150c00229791cc89ff309fff21";
  }

  static const char* value(const ::srv_sub_pub::AddTwoInts&) { return value(); }
};

template<>
struct DataType< ::srv_sub_pub::AddTwoInts > {
  static const char* value()
  {
    return "srv_sub_pub/AddTwoInts";
  }

  static const char* value(const ::srv_sub_pub::AddTwoInts&) { return value(); }
};


// service_traits::MD5Sum< ::srv_sub_pub::AddTwoIntsRequest> should match 
// service_traits::MD5Sum< ::srv_sub_pub::AddTwoInts > 
template<>
struct MD5Sum< ::srv_sub_pub::AddTwoIntsRequest>
{
  static const char* value()
  {
    return MD5Sum< ::srv_sub_pub::AddTwoInts >::value();
  }
  static const char* value(const ::srv_sub_pub::AddTwoIntsRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::srv_sub_pub::AddTwoIntsRequest> should match 
// service_traits::DataType< ::srv_sub_pub::AddTwoInts > 
template<>
struct DataType< ::srv_sub_pub::AddTwoIntsRequest>
{
  static const char* value()
  {
    return DataType< ::srv_sub_pub::AddTwoInts >::value();
  }
  static const char* value(const ::srv_sub_pub::AddTwoIntsRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::srv_sub_pub::AddTwoIntsResponse> should match 
// service_traits::MD5Sum< ::srv_sub_pub::AddTwoInts > 
template<>
struct MD5Sum< ::srv_sub_pub::AddTwoIntsResponse>
{
  static const char* value()
  {
    return MD5Sum< ::srv_sub_pub::AddTwoInts >::value();
  }
  static const char* value(const ::srv_sub_pub::AddTwoIntsResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::srv_sub_pub::AddTwoIntsResponse> should match 
// service_traits::DataType< ::srv_sub_pub::AddTwoInts > 
template<>
struct DataType< ::srv_sub_pub::AddTwoIntsResponse>
{
  static const char* value()
  {
    return DataType< ::srv_sub_pub::AddTwoInts >::value();
  }
  static const char* value(const ::srv_sub_pub::AddTwoIntsResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // SRV_SUB_PUB_MESSAGE_ADDTWOINTS_H
