// Generated by gencpp from file service2/MoveTask.msg
// DO NOT EDIT!


#ifndef SERVICE2_MESSAGE_MOVETASK_H
#define SERVICE2_MESSAGE_MOVETASK_H

#include <ros/service_traits.h>


#include <service2/MoveTaskRequest.h>
#include <service2/MoveTaskResponse.h>


namespace service2
{

struct MoveTask
{

typedef MoveTaskRequest Request;
typedef MoveTaskResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct MoveTask
} // namespace service2


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::service2::MoveTask > {
  static const char* value()
  {
    return "62cc619b2db1e9bc833b3a29d3a58227";
  }

  static const char* value(const ::service2::MoveTask&) { return value(); }
};

template<>
struct DataType< ::service2::MoveTask > {
  static const char* value()
  {
    return "service2/MoveTask";
  }

  static const char* value(const ::service2::MoveTask&) { return value(); }
};


// service_traits::MD5Sum< ::service2::MoveTaskRequest> should match 
// service_traits::MD5Sum< ::service2::MoveTask > 
template<>
struct MD5Sum< ::service2::MoveTaskRequest>
{
  static const char* value()
  {
    return MD5Sum< ::service2::MoveTask >::value();
  }
  static const char* value(const ::service2::MoveTaskRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::service2::MoveTaskRequest> should match 
// service_traits::DataType< ::service2::MoveTask > 
template<>
struct DataType< ::service2::MoveTaskRequest>
{
  static const char* value()
  {
    return DataType< ::service2::MoveTask >::value();
  }
  static const char* value(const ::service2::MoveTaskRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::service2::MoveTaskResponse> should match 
// service_traits::MD5Sum< ::service2::MoveTask > 
template<>
struct MD5Sum< ::service2::MoveTaskResponse>
{
  static const char* value()
  {
    return MD5Sum< ::service2::MoveTask >::value();
  }
  static const char* value(const ::service2::MoveTaskResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::service2::MoveTaskResponse> should match 
// service_traits::DataType< ::service2::MoveTask > 
template<>
struct DataType< ::service2::MoveTaskResponse>
{
  static const char* value()
  {
    return DataType< ::service2::MoveTask >::value();
  }
  static const char* value(const ::service2::MoveTaskResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // SERVICE2_MESSAGE_MOVETASK_H
