(cl:in-package my_pkg2-msg)
(cl:export '(BMANGDH-VAL
          BMANGDH
          BMANGVELDH-VAL
          BMANGVELDH
          AMANGDH-VAL
          AMANGDH
          AMANGVELDH-VAL
          AMANGVELDH
          BKANGDH-VAL
          BKANGDH
          BKANGVELDH-VAL
          BKANGVELDH
          RLANGDH-VAL
          RLANGDH
          RLANGVELDH-VAL
          RLANGVELDH
          PCANGDH-VAL
          PCANGDH
          PCANGVELDH-VAL
          PCANGVELDH
          HDANGDH-VAL
          HDANGDH
          HDANGVELDH-VAL
          HDANGVELDH
          YWANGDH-VAL
          YWANGDH
          YWANGVELDH-VAL
          YWANGVELDH
          GNSSPOSEAST-VAL
          GNSSPOSEAST
          GNSSPOSNORTH-VAL
          GNSSPOSNORTH
          GNSSPOSUP-VAL
          GNSSPOSUP
          GNSSVELEAST-VAL
          GNSSVELEAST
          GNSSVELNORTH-VAL
          GNSSVELNORTH
          GNSSVELUP-VAL
          GNSSVELUP
          GNSSVELX-VAL
          GNSSVELX
          BMANGLECMD-VAL
          BMANGLECMD
          BMANGLEVELCMD-VAL
          BMANGLEVELCMD
          BKANGLECMD-VAL
          BKANGLECMD
          BKANGLEVELCMD-VAL
          BKANGLEVELCMD
          AMANGLECMD-VAL
          AMANGLECMD
          AMANGLEVELCMD-VAL
          AMANGLEVELCMD
          SWANGLECMD-VAL
          SWANGLECMD
          SWANGLEVELCMD-VAL
          SWANGLEVELCMD
))